openapi: 3.0.3
info:
  title: Network Health Assessment
  description: |
    Network Insight offers a unified analytical platform for specific networks, such as private networks and slices, focusing exclusively on aggregated network-level data rather than individual device information.
    It empowers users to both evaluate the overall network health through a comprehensive, component-based scoring system and to analyze service traffic patterns with customizable granularity.
    By providing a holistic view — from infrastructure health to user traffic trends — this API suite delivers the critical, real-time data needed for comprehensive network monitoring, strategic performance optimization, and effective early warning systems.

    # Introduction

    This API allows users to query the health score of a specified network, which consists of multiple components including the wireless network, transmission network, and core network.
    By calculating the health score for each component and then applying weighted calculations, the API provides a comprehensive health score result for the specified network.

    # API functionality

    The API provides the following functionality:
    - Query the health scores of different network modules in the specify network at the latest point in time.

    # Request Parameters Definition:
    * **module**: Modules within the network. Optional parameters are: net (the entire network), net_wireless (wireless network), net_transnet (transport network), net_core (core network).

    # Authorization and authentication

    The "Camara Security and Interoperability Profile" provides details of how an API consumer requests an access token. Please refer to Identity and Consent Management (https://github.com/camaraproject/IdentityAndConsentManagement/) for the released version of the profile.

    The specific authorization flows to be used will be agreed upon during the onboarding process, happening between the API consumer and the API provider, taking into account the declared purpose for accessing the API, whilst also being subject to the prevailing legal framework dictated by local legislation.

    In cases where personal data is processed by the API and users can exercise their rights through mechanisms such as opt-in and/or opt-out, the use of three-legged access tokens is mandatory. This ensures that the API remains in compliance with privacy regulations, upholding the principles of transparency and user-centric privacy-by-design.

    This API requires users to provide user information via request header signature authentication. By using the AccessKeyId (user account), SignatureNonce (random unique identifier), Version (date identifier), Timestamp (timestamp), and Signature (calculated from other request headers using an encryption algorithm) fields in the request headers, the API verifies the Signature. Upon verification, the API accepts the value in AccessKeyId as the user identity to match user data.

    # Additional CAMARA error responses

    The list of error codes in this API specification is not exhaustive. Therefore the API specification may not document some non-mandatory error statuses as indicated in `CAMARA API Design Guide`.

    Please refer to the `CAMARA_common.yaml` of the Commonalities Release associated to this API version for a complete list of error responses. The applicable Commonalities Release can be identified in the `API Readiness Checklist` document associated to this API version.

    As a specific rule, error `501 - NOT_IMPLEMENTED` can be only a possible error response if it is explicitly documented in the API.
  version: 0.1.0-rc.1
  contact:
    email: sp-network-insights@lists.camaraproject.org
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
externalDocs:
  description: Project documentation at CAMARA
  url: https://github.com/camaraproject/NetworkInsights
servers:
  - url: '{apiRoot}/ecop-boss/ne-health/network_score_lastest/v0.1rc1'
    variables:
      apiRoot:
        default: http://localhost:9091
        description: API root
tags:
  - name: Network lastest Score
    description: This API allows users to query the health score of a specified network, which consists of multiple components including the wireless network, transmission network, and core network. By calculating the health score for each component and then applying weighted calculations, the API provides a comprehensive health score result for the specified network.
paths:
  /network-score-lastest:
    get:
      tags:
        - Network lastest Score
      summary: Query the latest time point network health score.
      description: |
        Query the health assessment results of the network.
        - The health score at the latest time point.
      operationId: struct
      parameters:
        - in: header
          name: SignatureNonce
          required: true
          description: A Universally Unique Identifier (UUID) for the specific item.
          schema:
            type: string
        - in: header
          name: Version
          required: true
          description: The date in yyyy-MM-dd format.
          schema:
            type: string
        - in: header
          name: AccessKeyId
          required: true
          description: The customer’s account name on the network management platform.
          schema:
            type: string
        - in: header
          name: Timestamp
          required: true
          description: The timestamp of the event in UTC.
          schema:
            type: string
        - in: header
          name: Signature
          required: true
          description: An encrypted result string generated from other request headers and a secret key, used for request validation.
          schema:
            type: string
        - in: query
          name: structCode
          required: true
          description: module of Network
          schema:
            type: string
            enum: [net, net_wireless, net_transnet, net_core]
            example: net_wireless
      responses:
        '200':
          description: Successful response with the network score struct.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    description: The status code of the response.
                  message:
                    type: string
                    description: A message indicating the success of the query.
                  data:
                    type: object
                    properties:
                      time:
                        type: string
                        description: The time of the score create.
                      valid:
                        type: integer
                        description: The validity of the score.
                      value:
                        type: string
                        description: The score of the health.
        '400':
          $ref: '#/components/responses/Generic400'
      security:
        - SignatureNonceAuth: []
          VersionAuth: []
          AccessKeyIdAuth: []
          TimestampAuth: []
          SignatureAuth: []
components:
  securitySchemes:
    SignatureNonceAuth:
      type: apiKey
      in: header
      name: SignatureNonce
      description: A Universally Unique Identifier (UUID) for the specific item.
    VersionAuth:
      type: apiKey
      in: header
      name: Version
      description: The date in yyyy-MM-dd format.
    AccessKeyIdAuth:
      type: apiKey
      in: header
      name: AccessKeyId
      description: The customer’s account name on the network management platform.
    TimestampAuth:
      type: apiKey
      in: header
      name: Timestamp
      description: The timestamp of the event in UTC.
    SignatureAuth:
      type: apiKey
      in: header
      name: Signature
      description: |
        Custom signature authentication.
        Generate the encrypted signature string by combining the following request header parameters:
        SignatureNonce, Version, AccessKeyId, Timestamp,
        and the fixed parameters SignatureVersion (fixed: 1.0), Format (fixed: JSON),
        and SignatureMethod (fixed: HMAC-SHA1).
        Signature Generation Process:
        1. URL-encode all request parameters.
        2. Sort the parameters lexicographically by their keys.
        3. Concatenate the sorted key-value pairs into a single string.
        4. Prepare the signature string, which includes the HTTP method and the URL-encoded parameter string, in the format: POST&%2F&<encoded_parameters>.
        5. Sign the string using the user’s secret key and the HMAC-SHA1 algorithm.
        6. Encode the resulting signature using Base64.
        Signature Verification Process:
        1. Receive the API request, including the request parameters and the Base64-encoded signature(header:Signature).
        2. Regenerate the signature using the same steps as in the signature generation process.
        3. Compare the received signature with the regenerated signature.
        4. If the two signatures match, the verification passes, indicating that the request is intact and from a trusted source.
        5. If the signatures do not match, the verification fails, suggesting that the request may have been tampered with or an error occurred during transmission.

  responses:
    Generic400:
      description: Problem with the client request
      content:
        application/json:
          examples:
            MissingQueryParameter:
              summary: Example of missing required query parameter
              value:
                status: 400
                data: null
                message: "Required string parameter 'structCode' is not present"
            MissingHeaderParameter:
              summary: Example of missing required header parameter
              value:
                status: 400
                data: null
                message: "Required header 'Signature' is not present."
            AuthenticationFailed:
              summary: Example of authentication failed
              value:
                status: 400
                data: null
                message: "Authentication failed"
